version: '3.8'

services:
  db:
    container_name: nextcloud_mariadb
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD=/run/secrets/mysql_password
      - MYSQL_DATABASE=/run/secrets/mysql_db
      - MYSQL_USER=/run/secrets/mysql_user
    secrets:
      - mysql_db
      - mysql_password
      - mysql_user
      - mysql_root_password
    networks: 
      - nextcloud_network

  app:
    container_name: nextcloud_app
    image: nextcloud
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DB_FILE=/run/secrets/mysql_db
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_db
      - mysql_password
      - mysql_root_password
      - mysql_user
    networks: 
      - nextcloud_network
    
  web:
    container_name: nextcloud_nginx
    image: nginx
    restart: always
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/html:/usr/share/nginx/html/:rw
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/configure/:/etc/nginx/conf.d/:ro
      - ./nginx/logs/:/var/log/nginx/
    networks: 
      - nextcloud_network

  onlyoffice:
    container_name: nextcloud_onlyoffice
    image: onlyoffice/documentserver
    restart: always
    volumes:
      - ./onlyoffice/logs:/var/log/onlyoffice
      #- ./onlyoffice/data:/var/www/onlyoffice/Data
      #- ./certs/onlyoffice.key:/app/onlyoffice/DocumentServer/data/certs/
      #- ./certs/onlyoffice.crt:/app/onlyoffice/DocumentServer/data/certs/
      #- ./certs/dhparam.pem:/app/onlyoffice/DocumentServer/data/certs/
      #- ./certs/:/app/onlyoffice/DocumentServer/data/certs/onlyoffice.key
      - ./certs/:/var/www/onlyoffice/Data
    command: bash -c "
                chmod 400 /app/onlyoffice/DocumentServer/data/certs/onlyoffice.key "
    networks: 
      - nextcloud_network

networks:
  nextcloud_network:
    name: nextcloud_network

secrets:
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt # put admin username to this file
  mysql_db:
    file: ./secrets/mysql_db.txt # put mysql db name to this file
  mysql_password:
    file: ./secrets/mysql_password.txt # put mysql password to this file
  mysql_user:
    file: ./secrets/mysql_user.txt # put mysql username to this file
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt # put mysql root password to this file